/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/card-link` | `/card-link`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/enhanced-reveal` | `/enhanced-reveal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/initial-taste` | `/initial-taste`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/quiz` | `/quiz`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pulse` | `/pulse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vault` | `/vault`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/card-link` | `/card-link`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/enhanced-reveal` | `/enhanced-reveal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/initial-taste` | `/initial-taste`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/quiz` | `/quiz`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pulse` | `/pulse`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vault` | `/vault`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verify${`?${string}` | `#${string}` | ''}` | `/verify${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/card-link${`?${string}` | `#${string}` | ''}` | `/card-link${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/enhanced-reveal${`?${string}` | `#${string}` | ''}` | `/enhanced-reveal${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/initial-taste${`?${string}` | `#${string}` | ''}` | `/initial-taste${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/quiz${`?${string}` | `#${string}` | ''}` | `/quiz${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/discover${`?${string}` | `#${string}` | ''}` | `/discover${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pulse${`?${string}` | `#${string}` | ''}` | `/pulse${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vault${`?${string}` | `#${string}` | ''}` | `/vault${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/card-link` | `/card-link`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/enhanced-reveal` | `/enhanced-reveal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/initial-taste` | `/initial-taste`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/quiz` | `/quiz`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pulse` | `/pulse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vault` | `/vault`; params?: Router.UnknownInputParams; };
    }
  }
}
